FROM python:3.6

WORKDIR /usr/src/app

RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get -y install curl

COPY ./feature-tests/requirements.txt ./

RUN pip install  --upgrade pip && pip install -r requirements.txt

ENTRYPOINT [ "./runtests.sh" ]