version: "3"
services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile-server
    volumes:
      - ./server:/usr/src/app
    ports:
      - 4000:5000
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      # Postgres will create the DB with this name and user if needed
      POSTGRES_DB:
      # The next values will be read from .env file
      POSTGRES_USER:
      POSTGRES_PASSWORD:

  db:
    container_name: db
    image: postgres:9-alpine
    ports:
      - 127.0.0.1:5432:5432
    environment:
      # Postgres will create the DB with this name and user if needed
      POSTGRES_DB:
      # The next values will be read from .env file
      POSTGRES_USER:
      POSTGRES_PASSWORD:

  test:
    container_name: test
    build:
        context: ./feature-tests
        dockerfile: Dockerfile-feature-tests
    volumes:
      - ./feature-tests:/usr/src/app
    depends_on:
      - db
      - server
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD: