FROM python:3.6

RUN apt-get update && apt-get -y install \
    python-pip \
    python-dev \
    libpq-dev \
    libmysqlclient-dev

ARG http_proxy="$http_proxy"
ARG https_proxy="$http_proxy"

WORKDIR /usr/src/app
COPY ./requirements.txt ./
RUN pip install --upgrade pip && pip install -r requirements.txt

ENV FLASK_APP=app.py
EXPOSE 5000
VOLUME /usr/src/app
CMD flask run --reload --host 0.0.0.0