FROM python:3.6


RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get -y install curl

WORKDIR /usr/src/app

COPY ./requirements.txt ./
RUN pip install  --upgrade pip && pip install -r requirements.txt

# BEHAVE_TAGS must be a comma separated list of strings. It may be empty
ARG BEHAVE_TAGS
ENV TAGS=${BEHAVE_TAGS}
ENTRYPOINT ["/bin/bash", "-c", "./tests.sh $TAGS"]
